### ISSUE TITLE
Core SDK Bugs #3: inconsistent output to console

### ISSUE THREAD

**Issue by ahsanazim** [ahsanazim/thesis#3]
only a subset of the desired output is being displayed to console/output-window

Hypothesis: 

- the missing output is being displayed, but in a color that matches that of the background
- or perhaps it's a C# thing? not related to the coreSDK?

**Comment by timofei7** [comment]
not sure what this might be, but i noticed that in the past the event stream was pretty noise,  you might have a start fixation followed by no end fixation but just another start fixation - in those cases just have to computer.  i had a little state machine to processes the event stream.  not sure if this is the same issue at all?

**Comment by ahsanazim** [comment]
perhaps was related to issue #2 perhaps, fixed itself with trial and error ... hasn't popped up again
